insert into authors (id, first_name, last_name) values (1, 'Giselle', 'Sire');
insert into authors (id, first_name, last_name) values (2, 'Gerry', 'Billinge');
insert into authors (id, first_name, last_name) values (3, 'Arlan', 'Jobbins');
insert into authors (id, first_name, last_name) values (4, 'Mallissa', 'Foley');
insert into authors (id, first_name, last_name) values (5, 'Jeri', 'Barling');
insert into authors (id, first_name, last_name) values (6, 'Kristoforo', 'Jeaneau');
insert into authors (id, first_name, last_name) values (7, 'Ange', 'Duthy');
insert into authors (id, first_name, last_name) values (8, 'Filmer', 'Baldam');
insert into authors (id, first_name, last_name) values (9, 'Benoite', 'Latchford');
insert into authors (id, first_name, last_name) values (10, 'Ariana', 'Ruddiforth');
insert into authors (id, first_name, last_name) values (11, 'Gibby', 'Cluckie');
insert into authors (id, first_name, last_name) values (12, 'Rickard', 'Lamborne');
insert into authors (id, first_name, last_name) values (13, 'Willi', 'Meneo');
insert into authors (id, first_name, last_name) values (14, 'Lorri', 'Eberz');
insert into authors (id, first_name, last_name) values (15, 'Annabela', 'Yacob');
insert into authors (id, first_name, last_name) values (16, 'Doris', 'ducarme');
insert into authors (id, first_name, last_name) values (17, 'Mahalia', 'Giberd');
insert into authors (id, first_name, last_name) values (18, 'Booth', 'Lourenco');
insert into authors (id, first_name, last_name) values (19, 'Esme', 'Ghilardi');
insert into authors (id, first_name, last_name) values (20, 'Reuben', 'Thing');
insert into authors (id, first_name, last_name) values (21, 'Maribeth', 'Peart');


insert into books (id, price, price_old, title, author_id) values (1, 1046, 1868, 'Kanlam', 1);
insert into books (id, price, price_old, title, author_id) values (2, 1735, 1585, 'Stim', 2);
insert into books (id, price, price_old, title, author_id) values (3, 557, 3200, 'Gembucket', 3);
insert into books (id, price, price_old, title, author_id) values (4, 1821, 3633, 'Kanlam', 4);
insert into books (id, price, price_old, title, author_id) values (5, 1584, 1273, 'It', 5);
insert into books (id, price, price_old, title, author_id) values (6, 2545, 3938, 'Cardify', 6);
insert into books (id, price, price_old, title, author_id) values (7, 1691, 2992, 'Konklab', 7);
insert into books (id, price, price_old, title, author_id) values (8, 1034, 1372, 'Veribet', 8);
insert into books (id, price, price_old, title, author_id) values (9, 2242, 1215, 'Treeflex', 9);
insert into books (id, price, price_old, title, author_id) values (10, 1477, 2031, 'Sub-Ex', 10);
insert into books (id, price, price_old, title, author_id) values (11, 508, 1913, 'Cardify', 11);
insert into books (id, price, price_old, title, author_id) values (12, 1849, 1349, 'Fintone', 12);
insert into books (id, price, price_old, title, author_id) values (13, 1247, 1524, 'Keylex', 13);
insert into books (id, price, price_old, title, author_id) values (14, 998, 3044, 'Cardguard', 14);
insert into books (id, price, price_old, title, author_id) values (15, 892, 3604, 'Matsoft', 15);
insert into books (id, price, price_old, title, author_id) values (16, 1726, 1018, 'Lotlux', 16);
insert into books (id, price, price_old, title, author_id) values (17, 2498, 1091, 'Viva', 17);
insert into books (id, price, price_old, title, author_id) values (18, 2751, 1769, 'Voyatouch', 18);
insert into books (id, price, price_old, title, author_id) values (19, 2878, 3591, 'Daltfresh', 19);
insert into books (id, price, price_old, title, author_id) values (20, 2647, 3570, 'Lotlux', 20);
insert into books (id, price, price_old, title, author_id) values (21, 987, 3012, 'Lotlux', 21);