-- insert into authors (full_name) values ('Drucie Goodbourn');
-- insert into authors (full_name) values ('Marcia Aggiss');
-- insert into authors (full_name) values ('Giovanni Bigg');
-- insert into authors (full_name) values ('Duffie Eynon');
-- insert into authors (full_name) values ('Anselma McKennan');
-- insert into authors (full_name) values ('Gert Kira');
-- insert into authors (full_name) values ('Clerc Djakovic');
-- insert into authors (full_name) values ('Stacee Elsy');
-- insert into authors (full_name) values ('Dorotea Bonhill');
-- insert into authors (full_name) values ('Minni Bunney');
-- insert into authors (full_name) values ('Berty Gandley');
-- insert into authors (full_name) values ('Raynard Tesdale');
-- insert into authors (full_name) values ('Joanna Hutfield');
-- insert into authors (full_name) values ('Dannie Glidder');
-- insert into authors (full_name) values ('Timmie Adshede');
-- insert into authors (full_name) values ('Fernando Neads');
-- insert into authors (full_name) values ('Teddy Guilliland');
-- insert into authors (full_name) values ('Paloma Grebert');
-- insert into authors (full_name) values ('Kristos Usher');
-- insert into authors (full_name) values ('Darcey Rohmer');
-- insert into authors (full_name) values ('Cristie Isacsson');
-- insert into authors (full_name) values ('Lindsay Coutthart');
-- insert into authors (full_name) values ('Helyn Schneidar');
-- insert into authors (full_name) values ('Bette-ann Askem');
-- insert into authors (full_name) values ('Dom Robuchon');

insert into books (author_id, title, priceOld, price) values (1, 'exploit real-time e-commerce', '$203.23', '$43.37');
insert into books (author_id, title, priceOld, price) values (2, 'utilize real-time interfaces', '$260.31', '$35.96');
insert into books (author_id, title, priceOld, price) values (3, 'extend strategic e-services', '$272.00', '$151.04');
insert into books (author_id, title, priceOld, price) values (4, 'iterate integrated solutions', '$271.58', '$141.40');
insert into books (author_id, title, priceOld, price) values (5, 'cultivate magnetic e-commerce', '$278.43', '$54.44');
insert into books (author_id, title, priceOld, price) values (6, 'architect vertical ROI', '$282.54', '$102.61');
insert into books (author_id, title, priceOld, price) values (7, 'disintermediate extensible architectures', '$295.38', '$181.27');
insert into books (author_id, title, priceOld, price) values (8, 'extend leading-edge methodologies', '$283.08', '$97.96');
insert into books (author_id, title, priceOld, price) values (9, 'integrate one-to-one systems', '$258.51', '$52.25');
insert into books (author_id, title, priceOld, price) values (10, 'revolutionize 24/7 infrastructures', '$260.79', '$33.69');
insert into books (author_id, title, priceOld, price) values (11, 'enhance innovative e-services', '$256.54', '$160.98');
insert into books (author_id, title, priceOld, price) values (12, 'maximize 24/365 e-tailers', '$262.07', '$34.06');
insert into books (author_id, title, priceOld, price) values (13, 'scale integrated architectures', '$257.66', '$32.97');
insert into books (author_id, title, priceOld, price) values (14, 'e-enable frictionless web services', '$288.19', '$90.52');
insert into books (author_id, title, priceOld, price) values (15, 'strategize B2B channels', '$232.27', '$44.83');
insert into books (author_id, title, priceOld, price) values (16, 'syndicate compelling deliverables', '$287.45', '$101.89');
insert into books (author_id, title, priceOld, price) values (17, 'utilize bleeding-edge users', '$281.37', '$146.21');
insert into books (author_id, title, priceOld, price) values (18, 'cultivate 24/365 networks', '$270.99', '$184.76');
insert into books (author_id, title, priceOld, price) values (19, 'embrace plug-and-play platforms', '$278.36', '$77.71');
insert into books (author_id, title, priceOld, price) values (20, 'target innovative paradigms', '$298.94', '$130.01');
insert into books (author_id, title, priceOld, price) values (21, 'generate open-source e-business', '$276.57', '$113.25');
insert into books (author_id, title, priceOld, price) values (22, 'implement user-centric e-markets', '$254.70', '$115.31');
insert into books (author_id, title, priceOld, price) values (23, 'utilize magnetic supply-chains', '$279.70', '$77.86');
insert into books (author_id, title, priceOld, price) values (24, 'e-enable dot-com supply-chains', '$297.83', '$110.15');
insert into books (author_id, title, priceOld, price) values (25, 'facilitate efficient eyeballs', '$232.30', '$131.48');