package com.example.BookShopApp.data.model.author;

import com.example.BookShopApp.data.model.book.BookEntity;
import com.fasterxml.jackson.annotation.JsonIgnore;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import javax.persistence.*;
import java.util.ArrayList;
import java.util.List;

@Entity
@Table(name = "authors")
@ApiModel("data model of author entity")
public class AuthorEntity {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @ApiModelProperty("author id generated by db")
    private int id;
    @Column(columnDefinition = "VARCHAR(255)")
    @ApiModelProperty("author photo")
    private String photo;
    @Column(columnDefinition = "VARCHAR(255)")
    private String slug;
    @Column(columnDefinition = "VARCHAR(255)")
    @ApiModelProperty(value = "author name", example = "HH GG", position = 1)
    private String name;
    @Column(columnDefinition = "TEXT")
    @ApiModelProperty("author description")
    private String description;

    @JsonIgnore
    @OneToMany(mappedBy = "author")
    private List<BookEntity> bookList = new ArrayList<>();

    public AuthorEntity(List<String> authors) {
        if(authors != null){
            this.name = authors.toString();
        }
    }


    public AuthorEntity() {
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getPhoto() {
        return photo;
    }

    public void setPhoto(String photo) {
        this.photo = photo;
    }

    public String getSlug() {
        return slug;
    }

    public void setSlug(String slug) {
        this.slug = slug;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public List<BookEntity> getBookList() {
        return bookList;
    }

    public void setBookList(List<BookEntity> bookList) {
        this.bookList = bookList;
    }
}
